### ISSUE TITLE
decimation filter allows aliasing

### ISSUE THREAD

**Issue by hughh-xmos** [xmos/lib_mic_array#184] opened 2023-04-18 15:59 UTC
the attenuation of the 2 stage decimation filter is not enough. It looks like the cut-off (-6 dB point) is at the nyquist. the stopband should already be at the nyquist so the cutoff needs to be lower. There is only 10 dB of attenuation at 9.5 kHz which means energy from 8-12 kHz will be aliased. see the attached plot...

![image](https://user-images.githubusercontent.com/46711793/232833802-cab9192c-2554-4854-9f3a-cebc22752761.png)

Older versions of the decimation filter had 3 stages. see for example https://github.com/xmos/lib_mic_array/blob/e82b46f3a64be7df7a8f059333e96fb032526d11/lib_mic_array/src/fir/fir_design.py

I cant find the filter design script for the 2 stage decimator?!

**Comment by astewart-xmos** [comment] 2023-05-03 21:28
I agree, the issue appears to be the filter itself (rather than the xcore implementation).  I combined the first and second stage filters into a single equivalent (non-decimating) filter and this is the response it has

![image](https://user-images.githubusercontent.com/28442350/236050969-c6e1bf58-6aa3-43e2-9370-5e26c73b5fed.png)

Pretty sure the ripples beyond 8 kHz are getting aliased to produce the ripples Allan showed me in his 1 kHz tone test.  

The filter coefficients being used in lib_mic_array right now were given to me in a Python `pkl` file when I started working on the mic array library, so I never had the original filter design script. The stage1 and stage2 scripts in the library are just for converting the float filter into fixed-point data usable on xcore.

So it looks like we just need a different filter.  Already spoke to @Allan-xmos about getting new coefficients (ideally, a python script for generating the filter coefficients which can be checked into the library repo)

**Comment by henkmuller** [comment] 2023-05-04 07:45
Just to add a bit of background. The original filters were designed to block the noise floor of the microphones on real boards. In particular, many of the boards have a DC-DC converter which produces noise in the high frequencies. The most annoying frequency band to be polluted is the band around 1.536 MHz (Nyquist), which is close to the 1.5 MHz frequency on which some of the DC-DCs operate. Any noise that is between 1.528 and 1.536 MHz which can fold into the audible band very quickly.

From memory, the original filters were designed to attenuate that part of the spectrum beyond what you would expect simply because if you don't you end up with a spike in the spectrum. To demonstrate that we ran an FFT over microphone signal and displayed it (real-time xscope) and you can see this spike wandering about all over your audio frequencies.

**Comment by hughh-xmos** [comment] 2023-05-04 08:36
We have some raw pdm captures (thanks Jerry for the build) so can check if the filters really cause the ripple. Then we can start to think if we need to replace the decimator; whether that's just swapping out the coefficients or actually redesigning the structure a bit.

**Comment by hughh-xmos** [comment] 2023-05-04 09:28
@henkmuller we should be able to attenuate around 1.5 MHz fairly easily because it is so far from the passband.

i just had a quick look and if we had a stage 1 half band filter, we can get 80 dB attenuation from 1.48 MHz to nyquist and the filter only has 9 non-zero coefficients.

![image](https://user-images.githubusercontent.com/46711793/236165308-c9dc49c8-24a0-49d7-967d-e690e11388af.png)

**Comment by Allan-xmos** [comment] 2023-05-04 13:16
I made a test signal summing a 1kHz tone with a series of sine waves from 8-16kHz

```
fs = 3072000
t = 5

noise = np.sin(1000*2*np.pi*np.arange(fs*t)/fs)

for freq in np.arange(8000, 16000, 100):
    noise += np.sin(freq*2*np.pi*np.arange(fs*t)/fs)
```

This gives a similar ripple to that seen in the lab recordings

![image](https://user-images.githubusercontent.com/73177465/236215214-8e218796-bf99-4b29-ac67-27888524f53e.png)

**Comment by hughh-xmos** [comment] 2023-05-04 13:19
@Allan-xmos so is that filtered at all? Or do you mean the ripple is just from spectral leakage of the higher frequency tones?

**Comment by Allan-xmos** [comment] 2023-05-04 13:28
I used the filter coefficients from lib_mic_array, and polyphase filter functions from scipy, so the ripple is from the filter coefficients. Interestingly I didn't see the ripple when using a random noise signal as the input 

```
fs = 3072000
t = 5

noise = np.sin(1000*2*np.pi*np.arange(fs*t)/fs)

for freq in np.arange(8000, 16000, 100):
    noise += np.sin(freq*2*np.pi*np.arange(fs*t)/fs)

noise_1 = spsig.resample_poly(noise, 1, 32, window=coeff_32)
noise_2 = spsig.resample_poly(noise_1, 1, 6, window=coeff_6)
plt.psd(noise_2, Fs=16000)
```

**Comment by Allan-xmos** [comment] 2023-05-04 18:26
I ran the PDM recordings through the filters, and have been able to reproduce the ripple. If I change the second stage filter to have more attenuation I can lose the ripple beneath the noise floor. However, eyeballing it against Phenix's plots [here](https://xmos1.sharepoint.com/:w:/s/VoicePipelinePerformance/EdL8ARFM0u1MmH9sWfmVRWcB2tKmURxDr5ZwF18esxCBng?e=zoO7X3), it looks like the noise floor is still higher than the Infineon dev board.

![image](https://user-images.githubusercontent.com/73177465/236294493-eecb8902-e55f-460d-9717-4b110ce5fc34.png)

**Comment by hughh-xmos** [comment] 2023-05-23 10:48
The existing decimator is raising the noise floor in "silence" by 4 dBA. this could be affecting teams requirements which depend on background noise, e.g. 4.1.11 in teams audio spec v4, 6.7 in spec v5.

![image](https://github.com/xmos/lib_mic_array/assets/46711793/cb082bb0-82e0-4810-88c1-d3338d4aa575)

this graph was made by taking a recording of speech with the PDM capture build and then decimating to 16 kHz using the current lib_mic_array coefficients and then a prototype set. The speech level was measured using ITU p56 active speech level and was within 0.1 dB between the two sets of filter coefficients. Then the noise in the "silence" following the speech was measured. The spectra of the noise is shown in the graph.

The "ripple" at high frequency is due to aliasing of high frequency noise relating to inadequate attenuation during stage 1 of the pdm decimator. The a-weighted Leq (used in the teams audio spec requirements) is 4 dB louder with the existing coefficients than with the prototype.

**Comment by mbanth** [comment] 2023-09-26 11:15
@Allan-xmos and @ed-xmos, has this issue been resolved?

**Comment by Allan-xmos** [comment] 2023-09-26 12:28
Closed in https://github.com/xmos/lib_mic_array/pull/185

**Closed by Allan-xmos** 2023-09-26 12:28 UTC
